inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/TrailingEmptyLines:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    - 'Rakefile'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'melodic.gemspec'
    - 'Rakefile'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: non_integer

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix

Style/NumericLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# Style guidelines for string literals:
# Use double quotes for controller routes:
  # get "/" do
  #   Case.all.to_json
  # end
# Use double quotes for sentences & logger statements:
  # logger.info "Finding cases with opts #{filter_opts}, from params: #{params}"
# Use single quotes for array and hash access:
  # @vars['first_name'] = account[:first_name]
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrivialAccessors:
  AllowDSLWriters: true
