AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'node_modules/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/TrailingBlankLines:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'melodic.gemspec'
    - 'Rakefile'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: non_integer

Performance/Casecmp:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix

Style/NumericLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# Style guidelines for string literals:
# Use double quotes for controller routes:
  # get "/" do
  #   Case.all.to_json
  # end
# Use double quotes for sentences & logger statements:
  # logger.info "Finding cases with opts #{filter_opts}, from params: #{params}"
# Use single quotes for array and hash access:
  # @vars['first_name'] = account[:first_name]
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrivialAccessors:
  AllowDSLWriters: true
