language: ruby
sudo: false
rvm:
  - 2.3.1
gemfile:
  - test/gemfiles/rails_4_2.gemfile
  - test/gemfiles/rails_5_0.gemfile
  - test/gemfiles/rails_5_1.gemfile
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
env:
  global:
  - VERBOSE=1
script:
  bundle exec rubocop . --format tap --config .rubocop.yml && bundle exec rake --trace
